spring.application.name=application
server.address=0.0.0.0
server.port=${PORT:8080}
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=
gemini.imageApi.url=https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash-image:generateContent?key=
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
