spring.application.name=application
server.address=0.0.0.0
server.port=8080
gemini.api.key=AIzaSyDZZ27TjQqElrvpHkaUxIueKKz3pm6C32M
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=